# Generated by Django 4.0 on 2022-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_song_album_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
