# Generated by Django 4.0 on 2022-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
