# Generated by Django 4.0 on 2022-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_song_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_artist',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
