# Generated by Django 4.0 on 2022-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_song_viewers_remove_song_views_song_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media'),
        ),
    ]
