# Generated by Django 4.0 on 2022-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Song',
        ),
        migrations.AddField(
            model_name='song',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
    ]
